### PR TITLE
Display title in marker window

### PR DESCRIPTION
**Pull request by running-on-sunshine**
Changes in this branch:

- In main.js:
  - Added a new variable called infoWindowTitle to addInfoWindowContent() that would display the title in the marker's window when it is clicked
  - Renamed the other classes within addInfoWindowContent() for uniformity across class names
- In styles.css, gave the title bold styling

@clinturbin: Could you please help review this for me? 🙂

### CODE REVIEW

**Comment by clinturbin** [comment]
I really like changing the class names, it looks a lot better!

I was thinking that we could probably break the addInfoWindowContent function into a few smaller functions.  Maybe something like this:
```
var addInfoWindowContent = function (pin) {
    var infoWindowContent = document.createElement("div");
    infoWindowContent.classList.add("info-window");
    infoWindowContent.appendChild(infoWindowTitle(pin));
    infoWindowContent.appendChild(infoWindowImage(pin));
    return infoWindowContent;
};

var infoWindowTitle = function (pin) {
    var infoWindowTitle = document.createElement("p");
    infoWindowTitle.classList.add("info-window-title");
    infoWindowTitle.textContent = pin.title;
    return infoWindowTitle;
};

var infoWindowImage = function (pin) {
    var infoWindowImage = document.createElement("img");
    infoWindowImage.classList.add("info-window-image");
    infoWindowImage.setAttribute("src", pin.image);
    return infoWindowImage;
};
```

**Comment by running-on-sunshine** [comment]
Yes! Good call! 🙂

I was thinking the same thing about breaking the functions down into smaller chunks as well! Especially after seeing the how large size addInfoWindowContent() was getting! 😄

I'll update the branch with those changes!

**Comment by running-on-sunshine** [comment]
In this update:

- Split the addInfoWindowContent into smaller functions as per suggestions (see main.js).

@clinturbin: Could you please review? 🙂

**Comment by clinturbin** [comment]
Looks good! OK to merge.👍

**Pull request merged**
