### PR TITLE
Added visibility class to listingInfoDescription

### PR DESCRIPTION
**Pull request by running-on-sunshine**
Changes in this branch: 

- Added a visibility class to var listingInfoDescription (see: scripts/main.js) in order to hide each listing's description when viewing on mobile. 
- On mobile, visibility is set to hidden (see: stylesheets/styles.css).
- On media query 768px+, visibility is set to visible (see: stylesheets/styles.css).

@clinturbin: Could you please help review? 🙂

### CODE REVIEW

**Comment by clinturbin** [comment]
Maybe we could change the class name of "visibility" to something like "listing-description-visibility" since the styling only really applies to that element at different screen sizes.

**Comment by running-on-sunshine** [comment]
This is a great suggestion! I like this suggestion! 😊

Changing the class name from 'visibility' to 'listing-description-visibility' or 'description-visibility' would make it easily understood while reading through both the main.js and styles.css files.

**Comment by running-on-sunshine** [comment]
Hi @clinturbin!

Update in this latest commit: 

- Took your suggestion and renamed the var listingInfoDescription class from 'visibility' to 'description-visibility' to be more descriptive (see: main.js and styles.css for updates). 🙂

Would you please help review again?

**Comment by clinturbin** [comment]
Looks good! Ok to merge👍

**Pull request merged**
